services:

  file-service:
    build:
      context: ./file-service
      dockerfile: Dockerfile
    ports:
      - "52001:52001"
    volumes:
      - ./file-service:/app
      - file_service_local_files:/reports
      - file_service_cron_config:/var/spool/cron
      - file_service_database:/data
      - file_service_config:/config
    environment:
      - PYTHONUNBUFFERED=1
    env_file:
      - ./.env
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - app-network


networks:
  app-network:
    driver: bridge

volumes:
  file_service_local_files:
  file_service_cron_config:
  file_service_database:
  file_service_config: