services:

  telegram-bot-service:
    build:
      context: ./telegram-bot-service
      dockerfile: Dockerfile
    env_file:
      - ./.env
    ports:
      - "7998:7998"
    volumes:
      - ./telegram-bot-service:/app
    environment:
      - PYTHONUNBUFFERED=1
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  file_service_local_files:
  file_service_cron_config:
  file_service_database:
  file_service_config: